project:
  type: book

book:
  title: "MECH230 Dynamics Notes"
  author: "Theresa Honein"
  date: "3/16/2026"
  chapters:
    - index.qmd
    - active_learning.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



