project:
  type: book


title: "MECH230 Dynamics Notes"
author: "Theresa Honein"
date: "Spring 2026"
number-sections: true

book:
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2 # This ensures ## sections are visible/expanded by default
  chapters:
    - index.qmd
    - part: "Preliminaries"
      chapters:
        - preliminaries/active_learning.qmd
        # - preliminaries/notation.qmd
    - part: "Rigid Body Dynamics"
      chapters: 
        - rigid_body_dynamics/rigid_body_kinematics.qmd
        - rigid_body_dynamics/rigid_body_kinetics.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib


format:
  html:
    theme:
      - cosmo # Try: lumen, flatly, quartz, or materia
      - brand
  pdf:
    documentclass: scrreprt



