---
title: "Particle Kinetics"
---

## The Balance of Linear Momentum

A particle is endowed with an inertial measure $m$, called its mass.

The linear momentum of a particle is defined to be
\begin{align}
    {\bf G} = m{\bf v}.
\end{align}
Taking the time derivative:
\begin{align}
    \dot{\bf G} = \dot{m}{\bf v}+m\dot{\bf v}.
\end{align}

::: {.callout-tip title="Think!"}
**Question:** Can you think of systems whose mass is not conserved?

**Answer:** In this class, we consider cases where mass is conserved, i.e. $\dot{m} = 0$. This is not the case, for example, for a launching rocket that is losing mass. The $\dot{m}{\bf v}$ term is useful in control volume analysis.
:::

Then, in our case of interest:
\begin{align}
    \dot{\bf G} = m\dot{\bf v} = m{\bf a}.
\end{align}
We postulate the following balance law:
\begin{align}
    {\bf F} = \dot{\bf G},
\end{align}
where ${\bf F}$ is the resultant external force acting on the particle. This is known as the **Balance of Linear Momentum**, **Newton's Second Law**, or **Euler's First Law**.

**Important:** ${\bf a}$ here is the absolute acceleration vector of the particle.

::: {.callout-tip title="Think!"}
**Question:** Under what conditions is the linear momentum ${\bf G}$ conserved?

**Answer:** An unbalanced net force ${\bf F}\neq {\bf 0}$ results in a change of ${\bf G}$. If ${\bf F}={\bf 0}$, then ${\bf G}={\bf c}$ where ${\bf c}$ is a constant vector. This is Newton's First Law.
:::

If ${\bf c}={\bf 0}$, we recover statics.

### Representations and Projections

Vectors are represented on a basis. For example:
\begin{align}
    {\bf F} &= F_x{\bf E}_x+F_y{\bf E}_y+ F_z{\bf E}_z,\\
    {\bf a} &= a_x{\bf E}_x+a_y{\bf E}_y+a_z{\bf E}_z.
\end{align}

::: {.callout-tip title="Think!"}
**Question:** How many independent scalar equations can we obtain from ${\bf F}=m{\bf a}$? How do we obtain them?

**Answer:** We get useful scalar equations by projecting ${\bf F} = \dot{\bf G}$ along unit directions:
\begin{align}
    \lp{\bf F}=\dot{\bf G}\rp\cdot{\bf E}_x \implies F_x = ma_x.
\end{align}
:::

## Newton's Third Law

When dealing with the forces of interaction between particles, a particle and a rigid body, or rigid bodies, we also invoke Newton's third law: "For every action there is an equal and opposite reaction." For example, the force exerted by a surface on a particle is equal in magnitude and opposite in direction to the force exerted by the particle on the surface.
