# Fundamental concepts of solid mechanics

This section is adapted from chapter 1 of [Introduction to Solid Mechanics - An Integrated Approach](https://link.springer.com/book/10.1007/978-1-4614-6768-7) by Lubliner and Papadopoulos [@lubliner2017introduction].

## Mechanics
Mechanics, as a scientific discipline, is the study of the behavior of bodies subject to forces and displacements (and, to some extent, heating and cooling).

## Solid Mechanics
Solid mechanics is the branch of mechanics dealing specifically with solid bodies.

## Body
A body, for the purpose of mechanics, is a portion of matter that, at a given moment in time, occupies a certain region in space.

- **Particle** If the region occupied by the body can be idealized as being of negligible extent (and thus reducible to a point), the body is called a particle.
- **Finite Body** A body that is not reducible to a point is called a finite body.

## Continuum
A finite body occupying a connected region every portion of which contains some matter is called a continuous body or, simply, a continuum.

## Material Points
At any point in a region occupied by a continuum, the matter in its immediate (infinitesimal) neighborhood can also be thought of as constituting a particle, and we may thus speak of the particles (also called material points) of a continuum.

## Displacement
A body is said to undergo a displacement when some or all of its particles are moved to occupy different positions in space.

## Configuration
The correspondence between the particles and the positions occupied by them at a given time is known as the body's configuration.

## Deformation
The displacement of a body is said to be rigid if the distances between all pairs of particles are the same in any two configurations. Otherwise, the body is said to undergo deformation.

## Rigid bodies
Bodies that can undergo only rigid displacements are called rigid bodies. Bodies that are not rigid are deformable.

## Motion
Motion is said to occur when the body occupies a succession of different configurations continuously over time.

## Rigid Motion
A rigid motion is a motion that involves only rigid displacements.

## Velocity
The rate of change, in time, of the position of a particle is its velocity.

## Acceleration
The velocity may in turn change in time, and its rate of change is the acceleration. The motion of a body is called uniform if the acceleration of all the particles is zero; otherwise, it is called accelerated.

## Kinematics
The branch of mechanics dealing with the displacement and motion of bodies is called kinematics.

## Force
Forces are interactions between bodies that cause them to move, and more specifically to accelerate, relative to each other (unless prevented from doing so by other forces).

# Galileo, Kepler, Newton

## Gravitational force
All bodies on or near the earth are subject to the earth's gravitational force and, as shown by Galileo in his famous experiments, will fall toward the center of the earth (unless prevented from doing so by other forces) with the same acceleration; the magnitude of this acceleration is denoted by $g$.

## $F = ma$
It was later shown by Newton, on the basis of Kepler's laws of planetary motion, that the magnitude of the acceleration (with respect to a frame of reference based on the "fixed" stars) due to gravitational force between any two bodies (idealized as particles) is inversely proportional to the square of the distance between them, and for each body it is proportional to the quantity of matter (or mass) of the other body. The product of mass and acceleration is therefore equal and opposite for the two bodies and may be identified with the force exerted on each body by the other.

## Equilibrium
If a body's acceleration is zero, then it is at rest or in a uniform motion. In this case, the forces is said to be in equilibrium. The study of equilibrium is known as statics and constitutes one of the main subjects of this book. Traditionally, statics deals only (or at least primarily) with rigid bodies, while deformable bodies are studied in courses historically called strength of materials (or, more recently, mechanics of materials). In this book [@lubliner2017introduction], the statics of rigid and deformable solid bodies will be studied in an integrated manner.